language: php
php:
  - '7.0'
  - '7.1'
services:
  - sqlite3

install: composer install

after_success:
  - php vendor/bin/coveralls --coverage_clover ${TRAVIS_BUILD_DIR}/.resource/coverage/clover.xml --verbose